version: '3.8'

services:
  db-users:
    image: postgres:16.3-alpine
    container_name: pgdb-users
    restart: always
    ports:
      - '5432:5432'
    env_file:
        - ./secrets/db_users.env

  db-events:
    image: postgres:17.0-alpine3.20
    container_name: pgdb-events
    restart: always
    ports:
      - '5433:5432'
    env_file:
        - ./secrets/db_events.env

  cache-db:
    image: redis:7.2.5
    container_name: redis-db
    restart: always
    ports:
      - '6379:6379'

  users-manager:
    build:
      context: .
      dockerfile: manager-users/Dockerfile
    container_name: users-manager
    restart: always
    ports:
      - '50051:80'
    env_file:
      - ./secrets/db_users.env
    environment:
      - POSTGRES_HOST=pgdb-users
      - POSTGRES_PORT=5432

  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: auth
    restart: always
    ports:
      - '8000:80'
    environment:
      - USERS_MANAGER_HOST=users-manager
      - USERS_MANAGER_PORT=80

volumes:
  db:
    driver: local